### ISSUE TITLE
Bug lorsque j'execute l'analyse

### ISSUE THREAD

**Issue by ET-AD** [caronpe/AndroidPictureAnalyser#2]
Je suppose que tu n'as pas ce problème.
Je vais push un correctif demain (je ne peux rien faire au boulot...). 
Tiens moi au courant si cela change quelque chose de ton côté.

![androidbug](https://cloud.githubusercontent.com/assets/10976583/11062899/156433ae-87b3-11e5-9c69-1b4ff37890ae.png)

**Comment by caronpe** [comment]
Négatif Étienne je n ai pas ce pb.  Penses bien à pull le projet pour avoir
la dernière version

**Comment by ET-AD** [comment]
Ok c'est bien de mon côté uniquement alors.
J'ai bien la dernière version sur GitHub "Version 1 viable". 03618fd8bb222a56724f2cbfc2a279117b6e45f6

Je te tiendrais au courant ici "du pourquoi et du comment" ;)

**Comment by ET-AD** [comment]
Erreur résolue. 
Peux tu m'indiquer si cela fonctionne toutjours de ton côté ?

Liens qui m'ont permis de comprendre et résoudre le bug : 
http://stackoverflow.com/questions/477572/strange-out-of-memory-issue-while-loading-an-image-to-a-bitmap-object
http://stackoverflow.com/questions/24135445/pre-guess-size-of-bitmap-from-the-actual-uri-before-scale-loading

**Comment by ET-AD** [comment]
Voila, je pense que cette fois-ci l'erreur est définitivement résolue.

Test de ton côté et tiens moi au courant ;)

**Comment by caronpe** [comment]
test de mon coté effectué. Rien ne change pour moi donc c'est ok!
